//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace bugtracker {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet5 : DataSet {
        
        private STATEDataTable tableSTATE;
        
        public DataSet5() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet5(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["STATE"] != null)) {
                    this.Tables.Add(new STATEDataTable(ds.Tables["STATE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public STATEDataTable STATE {
            get {
                return this.tableSTATE;
            }
        }
        
        public override DataSet Clone() {
            DataSet5 cln = ((DataSet5)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["STATE"] != null)) {
                this.Tables.Add(new STATEDataTable(ds.Tables["STATE"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableSTATE = ((STATEDataTable)(this.Tables["STATE"]));
            if ((this.tableSTATE != null)) {
                this.tableSTATE.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet5";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet5.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableSTATE = new STATEDataTable();
            this.Tables.Add(this.tableSTATE);
        }
        
        private bool ShouldSerializeSTATE() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void STATERowChangeEventHandler(object sender, STATERowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class STATEDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnID;
            
            private DataColumn columnNAME;
            
            internal STATEDataTable() : 
                    base("STATE") {
                this.InitClass();
            }
            
            internal STATEDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            internal DataColumn NAMEColumn {
                get {
                    return this.columnNAME;
                }
            }
            
            public STATERow this[int index] {
                get {
                    return ((STATERow)(this.Rows[index]));
                }
            }
            
            public event STATERowChangeEventHandler STATERowChanged;
            
            public event STATERowChangeEventHandler STATERowChanging;
            
            public event STATERowChangeEventHandler STATERowDeleted;
            
            public event STATERowChangeEventHandler STATERowDeleting;
            
            public void AddSTATERow(STATERow row) {
                this.Rows.Add(row);
            }
            
            public STATERow AddSTATERow(System.Guid ID, string NAME) {
                STATERow rowSTATERow = ((STATERow)(this.NewRow()));
                rowSTATERow.ItemArray = new object[] {
                        ID,
                        NAME};
                this.Rows.Add(rowSTATERow);
                return rowSTATERow;
            }
            
            public STATERow FindByID(System.Guid ID) {
                return ((STATERow)(this.Rows.Find(new object[] {
                            ID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                STATEDataTable cln = ((STATEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new STATEDataTable();
            }
            
            internal void InitVars() {
                this.columnID = this.Columns["ID"];
                this.columnNAME = this.Columns["NAME"];
            }
            
            private void InitClass() {
                this.columnID = new DataColumn("ID", typeof(System.Guid), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID);
                this.columnNAME = new DataColumn("NAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNAME);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnID}, true));
                this.columnID.AllowDBNull = false;
                this.columnID.Unique = true;
                this.columnNAME.AllowDBNull = false;
            }
            
            public STATERow NewSTATERow() {
                return ((STATERow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new STATERow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(STATERow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.STATERowChanged != null)) {
                    this.STATERowChanged(this, new STATERowChangeEvent(((STATERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.STATERowChanging != null)) {
                    this.STATERowChanging(this, new STATERowChangeEvent(((STATERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.STATERowDeleted != null)) {
                    this.STATERowDeleted(this, new STATERowChangeEvent(((STATERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.STATERowDeleting != null)) {
                    this.STATERowDeleting(this, new STATERowChangeEvent(((STATERow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveSTATERow(STATERow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class STATERow : DataRow {
            
            private STATEDataTable tableSTATE;
            
            internal STATERow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableSTATE = ((STATEDataTable)(this.Table));
            }
            
            public System.Guid ID {
                get {
                    return ((System.Guid)(this[this.tableSTATE.IDColumn]));
                }
                set {
                    this[this.tableSTATE.IDColumn] = value;
                }
            }
            
            public string NAME {
                get {
                    return ((string)(this[this.tableSTATE.NAMEColumn]));
                }
                set {
                    this[this.tableSTATE.NAMEColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class STATERowChangeEvent : EventArgs {
            
            private STATERow eventRow;
            
            private DataRowAction eventAction;
            
            public STATERowChangeEvent(STATERow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public STATERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
