//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace bugtracker {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet3 : DataSet {
        
        private PRIORITYDataTable tablePRIORITY;
        
        public DataSet3() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet3(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["PRIORITY"] != null)) {
                    this.Tables.Add(new PRIORITYDataTable(ds.Tables["PRIORITY"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PRIORITYDataTable PRIORITY {
            get {
                return this.tablePRIORITY;
            }
        }
        
        public override DataSet Clone() {
            DataSet3 cln = ((DataSet3)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["PRIORITY"] != null)) {
                this.Tables.Add(new PRIORITYDataTable(ds.Tables["PRIORITY"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablePRIORITY = ((PRIORITYDataTable)(this.Tables["PRIORITY"]));
            if ((this.tablePRIORITY != null)) {
                this.tablePRIORITY.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet3";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet3.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablePRIORITY = new PRIORITYDataTable();
            this.Tables.Add(this.tablePRIORITY);
        }
        
        private bool ShouldSerializePRIORITY() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void PRIORITYRowChangeEventHandler(object sender, PRIORITYRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PRIORITYDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnID;
            
            private DataColumn columnNAME;
            
            internal PRIORITYDataTable() : 
                    base("PRIORITY") {
                this.InitClass();
            }
            
            internal PRIORITYDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            internal DataColumn NAMEColumn {
                get {
                    return this.columnNAME;
                }
            }
            
            public PRIORITYRow this[int index] {
                get {
                    return ((PRIORITYRow)(this.Rows[index]));
                }
            }
            
            public event PRIORITYRowChangeEventHandler PRIORITYRowChanged;
            
            public event PRIORITYRowChangeEventHandler PRIORITYRowChanging;
            
            public event PRIORITYRowChangeEventHandler PRIORITYRowDeleted;
            
            public event PRIORITYRowChangeEventHandler PRIORITYRowDeleting;
            
            public void AddPRIORITYRow(PRIORITYRow row) {
                this.Rows.Add(row);
            }
            
            public PRIORITYRow AddPRIORITYRow(System.Guid ID, string NAME) {
                PRIORITYRow rowPRIORITYRow = ((PRIORITYRow)(this.NewRow()));
                rowPRIORITYRow.ItemArray = new object[] {
                        ID,
                        NAME};
                this.Rows.Add(rowPRIORITYRow);
                return rowPRIORITYRow;
            }
            
            public PRIORITYRow FindByID(System.Guid ID) {
                return ((PRIORITYRow)(this.Rows.Find(new object[] {
                            ID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                PRIORITYDataTable cln = ((PRIORITYDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new PRIORITYDataTable();
            }
            
            internal void InitVars() {
                this.columnID = this.Columns["ID"];
                this.columnNAME = this.Columns["NAME"];
            }
            
            private void InitClass() {
                this.columnID = new DataColumn("ID", typeof(System.Guid), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID);
                this.columnNAME = new DataColumn("NAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNAME);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnID}, true));
                this.columnID.AllowDBNull = false;
                this.columnID.Unique = true;
                this.columnNAME.AllowDBNull = false;
            }
            
            public PRIORITYRow NewPRIORITYRow() {
                return ((PRIORITYRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new PRIORITYRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(PRIORITYRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PRIORITYRowChanged != null)) {
                    this.PRIORITYRowChanged(this, new PRIORITYRowChangeEvent(((PRIORITYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PRIORITYRowChanging != null)) {
                    this.PRIORITYRowChanging(this, new PRIORITYRowChangeEvent(((PRIORITYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PRIORITYRowDeleted != null)) {
                    this.PRIORITYRowDeleted(this, new PRIORITYRowChangeEvent(((PRIORITYRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PRIORITYRowDeleting != null)) {
                    this.PRIORITYRowDeleting(this, new PRIORITYRowChangeEvent(((PRIORITYRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovePRIORITYRow(PRIORITYRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PRIORITYRow : DataRow {
            
            private PRIORITYDataTable tablePRIORITY;
            
            internal PRIORITYRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablePRIORITY = ((PRIORITYDataTable)(this.Table));
            }
            
            public System.Guid ID {
                get {
                    return ((System.Guid)(this[this.tablePRIORITY.IDColumn]));
                }
                set {
                    this[this.tablePRIORITY.IDColumn] = value;
                }
            }
            
            public string NAME {
                get {
                    return ((string)(this[this.tablePRIORITY.NAMEColumn]));
                }
                set {
                    this[this.tablePRIORITY.NAMEColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PRIORITYRowChangeEvent : EventArgs {
            
            private PRIORITYRow eventRow;
            
            private DataRowAction eventAction;
            
            public PRIORITYRowChangeEvent(PRIORITYRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public PRIORITYRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
