//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace OnlineDevelopmentPlatform {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class MainDataSet : DataSet {
        
        private PROJECTDataTable tablePROJECT;
        
        public MainDataSet() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected MainDataSet(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["PROJECT"] != null)) {
                    this.Tables.Add(new PROJECTDataTable(ds.Tables["PROJECT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PROJECTDataTable PROJECT {
            get {
                return this.tablePROJECT;
            }
        }
        
        public override DataSet Clone() {
            MainDataSet cln = ((MainDataSet)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["PROJECT"] != null)) {
                this.Tables.Add(new PROJECTDataTable(ds.Tables["PROJECT"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablePROJECT = ((PROJECTDataTable)(this.Tables["PROJECT"]));
            if ((this.tablePROJECT != null)) {
                this.tablePROJECT.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "MainDataSet";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/MainDataSet.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablePROJECT = new PROJECTDataTable();
            this.Tables.Add(this.tablePROJECT);
        }
        
        private bool ShouldSerializePROJECT() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void PROJECTRowChangeEventHandler(object sender, PROJECTRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PROJECTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnID;
            
            private DataColumn columnNAME;
            
            private DataColumn columnDESCRIPTION;
            
            private DataColumn columnPROJECTTYPEID;
            
            internal PROJECTDataTable() : 
                    base("PROJECT") {
                this.InitClass();
            }
            
            internal PROJECTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            internal DataColumn NAMEColumn {
                get {
                    return this.columnNAME;
                }
            }
            
            internal DataColumn DESCRIPTIONColumn {
                get {
                    return this.columnDESCRIPTION;
                }
            }
            
            internal DataColumn PROJECTTYPEIDColumn {
                get {
                    return this.columnPROJECTTYPEID;
                }
            }
            
            public PROJECTRow this[int index] {
                get {
                    return ((PROJECTRow)(this.Rows[index]));
                }
            }
            
            public event PROJECTRowChangeEventHandler PROJECTRowChanged;
            
            public event PROJECTRowChangeEventHandler PROJECTRowChanging;
            
            public event PROJECTRowChangeEventHandler PROJECTRowDeleted;
            
            public event PROJECTRowChangeEventHandler PROJECTRowDeleting;
            
            public void AddPROJECTRow(PROJECTRow row) {
                this.Rows.Add(row);
            }
            
            public PROJECTRow AddPROJECTRow(System.Guid ID, string NAME, string DESCRIPTION, System.Guid PROJECTTYPEID) {
                PROJECTRow rowPROJECTRow = ((PROJECTRow)(this.NewRow()));
                rowPROJECTRow.ItemArray = new object[] {
                        ID,
                        NAME,
                        DESCRIPTION,
                        PROJECTTYPEID};
                this.Rows.Add(rowPROJECTRow);
                return rowPROJECTRow;
            }
            
            public PROJECTRow FindByID(System.Guid ID) {
                return ((PROJECTRow)(this.Rows.Find(new object[] {
                            ID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                PROJECTDataTable cln = ((PROJECTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new PROJECTDataTable();
            }
            
            internal void InitVars() {
                this.columnID = this.Columns["ID"];
                this.columnNAME = this.Columns["NAME"];
                this.columnDESCRIPTION = this.Columns["DESCRIPTION"];
                this.columnPROJECTTYPEID = this.Columns["PROJECTTYPEID"];
            }
            
            private void InitClass() {
                this.columnID = new DataColumn("ID", typeof(System.Guid), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID);
                this.columnNAME = new DataColumn("NAME", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNAME);
                this.columnDESCRIPTION = new DataColumn("DESCRIPTION", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDESCRIPTION);
                this.columnPROJECTTYPEID = new DataColumn("PROJECTTYPEID", typeof(System.Guid), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPROJECTTYPEID);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnID}, true));
                this.columnID.AllowDBNull = false;
                this.columnID.Unique = true;
                this.columnNAME.AllowDBNull = false;
                this.columnDESCRIPTION.AllowDBNull = false;
                this.columnPROJECTTYPEID.AllowDBNull = false;
            }
            
            public PROJECTRow NewPROJECTRow() {
                return ((PROJECTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new PROJECTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(PROJECTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PROJECTRowChanged != null)) {
                    this.PROJECTRowChanged(this, new PROJECTRowChangeEvent(((PROJECTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PROJECTRowChanging != null)) {
                    this.PROJECTRowChanging(this, new PROJECTRowChangeEvent(((PROJECTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PROJECTRowDeleted != null)) {
                    this.PROJECTRowDeleted(this, new PROJECTRowChangeEvent(((PROJECTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PROJECTRowDeleting != null)) {
                    this.PROJECTRowDeleting(this, new PROJECTRowChangeEvent(((PROJECTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovePROJECTRow(PROJECTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PROJECTRow : DataRow {
            
            private PROJECTDataTable tablePROJECT;
            
            internal PROJECTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablePROJECT = ((PROJECTDataTable)(this.Table));
            }
            
            public System.Guid ID {
                get {
                    return ((System.Guid)(this[this.tablePROJECT.IDColumn]));
                }
                set {
                    this[this.tablePROJECT.IDColumn] = value;
                }
            }
            
            public string NAME {
                get {
                    return ((string)(this[this.tablePROJECT.NAMEColumn]));
                }
                set {
                    this[this.tablePROJECT.NAMEColumn] = value;
                }
            }
            
            public string DESCRIPTION {
                get {
                    return ((string)(this[this.tablePROJECT.DESCRIPTIONColumn]));
                }
                set {
                    this[this.tablePROJECT.DESCRIPTIONColumn] = value;
                }
            }
            
            public System.Guid PROJECTTYPEID {
                get {
                    return ((System.Guid)(this[this.tablePROJECT.PROJECTTYPEIDColumn]));
                }
                set {
                    this[this.tablePROJECT.PROJECTTYPEIDColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PROJECTRowChangeEvent : EventArgs {
            
            private PROJECTRow eventRow;
            
            private DataRowAction eventAction;
            
            public PROJECTRowChangeEvent(PROJECTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public PROJECTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
